### ISSUE TITLE
"Local Servers" list is empty

### ISSUE THREAD

**Issue by Cyberbeni** [jellyfin/Swiftfin#683]
### Describe the bug

Since iOS 14, apps should trigger a permission prompt when trying to discover the local network: https://developer.apple.com/videos/play/wwdc2020/10110/

This doesn't happen in Swiftfin and the Local Servers list is also empty.

Here is the docker-compose.yaml that I use (also tried host network mode):

```yaml
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    mem_limit: '2g'
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.1.6:8096
    ports:
      - '1900:1900/udp' # DLNA
      - '7359:7359/udp' # service discovery
      - '8096:8096/tcp' # web UI
    hostname: Fuji
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ../samba/share/__media_server:/media
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - '109' # `cat /etc/group` and look for `render:x:109:` or similar
```

I am new to Jellyfin and I only tried the other mobile app yet but that doesn't seem to have a local servers feature, so I don't know if it is a server setting that I am missing.

### Application version

1.0.0 (79)

### Where did you install the app from?

App Store

### Device information

iPhone 11 Pro

### OS version

iOS 16.2

### Jellyfin server version

10.8.8
